authors = ["Riley Ballachay <riley.ballachay@gmail.com>"]
name = "PlasmoOld"
uuid = "2c8e550e-aa14-11ea-0b26-bb14ff6615fc"
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
